### ISSUE TITLE
Please add release tags

### ISSUE THREAD

**Issue by tillea** [ZoomerAnalytics/nose-random#1]
Hi,
I'm considering to package this project for Debian since it seems to be used in jsondiff tests.  It would be helpfuil if you would add a release tag to know what code you consider apropriate for a release.
Thank you, Andreas.

**Comment by fzumstein** [comment]
done. let me know if there's anything else you need.

**Comment by tillea** [comment]
On Wed, Jan 17, 2018 at 11:15:40AM +0000, Felix Zumstein wrote:
> done. let me know if there's anything else you need.

Thanks for the quick response, Andreas.

**Comment by tillea** [comment]
On Wed, Jan 17, 2018 at 11:15:40AM +0000, Felix Zumstein wrote:
> done. let me know if there's anything else you need.
Package is now in Debian.  Thank you.
